image: docker:28.3.0

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  # - lint
  # - secrets
  - build

# lint:
#   stage: lint
#   before_script:
#     - apt-get update && apt-get install -y nodejs npm
#     - npm install -g eslint prettier
#   script:
#     - npm ci
#     - npx eslint . --max-warnings=0

# prettier:
#   stage: lint
#   before_script:
#     - apt-get update && apt-get install -y nodejs npm
#     - npm install -g prettier
#   script:
#     - npm ci
#     - npx prettier --check .

# gitleaks-job:
#   stage: secrets
#   before_script:
#     - apt-get update && apt-get install -y wget
#     - wget -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.27.2/gitleaks_8.27.2_linux_x64.tar.gz
#     - tar xvzf gitleaks.tar.gz
#     - rm README.md
#     - mv gitleaks /usr/local/bin/gitleaks
#   script:
#     - gitleaks detect --source=. --no-git --verbose --redact
#   allow_failure: false

build:
  stage: build
  script:
    - docker info                           # vérifier que Docker fonctionne
    - docker build -t petfriendlylocator .  # remplace par ton vrai nom d'image