image: debian:12.11

stages:
  - lint
  - build

lint:
  image: node:22
  stage: lint
  script:
    - npm ci
    - npx eslint . --max-warnings=0

prettier:
  image: node:22
  stage: lint
  script:
    - npm ci
    - npx prettier --check .
