# Étape de base
FROM debian:12.11 AS base

# LABELS OCI standard pour métadonnées de l'image
LABEL org.opencontainers.image.title="Pet Friendly Locator" \
      org.opencontainers.image.description="Web app to locate pet-friendly places around Bordeaux" \
      org.opencontainers.image.authors="Periicles" \
      org.opencontainers.image.url="https://gitlab.com/Periicles/petfriendlybordeaux" \
      org.opencontainers.image.source="https://github.com/jeandoe/petfriendlylocator/blob/main/Dockerfile"

# Définir le répertoire de travail
WORKDIR /app

# Installer Node.js (exemple de runtime)
RUN apt-get update && \
    apt-get install -y curl gnupg ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances sans le cache
RUN npm install --omit=dev && \
    npm cache clean --force

# Copier le reste du code
COPY . .

# Générer le Prisma client et migrer
RUN npx prisma generate --schema=src/prisma/schema.prisma && \
    npx prisma migrate deploy --schema=src/prisma/schema.prisma

# Build de l'application
RUN npm run build

# Port exposé
EXPOSE 3000

# Lancement
ENTRYPOINT ["npm", "start"]
