# Dockerfile-prod
FROM node:22

WORKDIR /app

# Copie des dépendances
COPY package*.json ./
RUN npm install --production

# Copie du code
COPY . .

# Génération du Prisma client
RUN npx prisma generate --schema=src/prisma/schema.prisma
RUN npx prisma migrate deploy --schema=src/prisma/schema.prisma

# Build Next.js
RUN npm run build

# Variables d’environnement
ENV ENVIRONMENT=prod

# Port exposé
EXPOSE 3000

# Lancement
ENTRYPOINT ["npm", "start"]
